const express = require("express");
const router = express.Router();
const controller = require("../controllers/indexController");
router.get("/", controller.user.getAll);
router.get("/:username", controller.user.getUsername);
router.get("/userData/:id", controller.user.findUserData);
router.get("/aadeData/:id", controller.user.getAadeData);
router.post("/register", controller.user.createNew);
router.post("/login", controller.user.login);
router.post("/createUserData/:id", controller.user.insertUserData);
router.post("/insertAadeData/:id", controller.user.insertAadeData);
router.put("/", controller.user.editAt);
router.put("/userData/:id", controller.user.updateUserData);
router.put("/updateAadeData", controller.user.updateAadeData);
router.delete("/", controller.user.deleteUser);
module.exports = router;
